language: java
jdk: openjdk11
sudo: false

script:
  - "mvn cobertura:cobertura"
  - gem install dpl
  - dpl --provider=heroku --app=$DPL_APP_NAME --api-key=$DPL_API_KEY

after_success:
  - bash <(curl -s https://codecov.io/bash)